# export HF_ENDPOINT=https://hf-mirror.com
# python3 -m sglang.launch_server --model-path Qwen/Qwen2.5-7B-Instruct --host 0.0.0.0 --port 30002 --enable-metrics

models:
  - model_path: Qwen/Qwen2.5-7B-Instruct
    base_url: http://192.168.103.15:30002
    api_key: None
    sampling_params:
      max_tokens: 32768
      temperature: 0.6
      top_p: 0.95
      max_token_usage: 0.8
      max_num_queue_reqs: 10