# salloc -N 1 -n 4 --gres=gpu:1 -p RTX3090
# export HF_ENDPOINT=https://hf-mirror.com
# export PATH=/data1/public/cuda/cuda-12.4/bin:$PATH
# conda activate sglang
# python3 -m sglang.launch_server --model-path /home/hywang/Reasoning/Decentralized-Agents/models/DeepSeek-R1-Distill-Qwen-7B --host 0.0.0.0 --port 30002 --enable-metrics


server_params:
  ip: 127.0.0.1
  port: 5780
  policy: default_sglang
  offload_frequency: 0.0
  queue_frequency: 1.0
  accept_frequency: 1.0

ledger_params:
  initial_credit: 1000.0
  initial_staked: 1.0

models:
  - model_path: Qwen/Qwen3-8B
    base_url: http://192.168.102.19:30002
    api_key: None

    gen_params:
      max_tokens: 8192
      temperature: 0.0
      top_p: 0.95
    
    dispatch_params:
      target_token_usage: 0.7
