# salloc -N 1 -n 4 --gres=gpu:1 -p RTX3090
# export HF_ENDPOINT=https://hf-mirror.com
# export PATH=/data1/public/cuda/cuda-11.8/bin:$PATH
# conda activate vllm
# vllm serve /home/hywang/Reasoning/Decentralized-Agents/models/DeepSeek-R1-Distill-Qwen-7B --max-model-len=36000 --host 0.0.0.0 --port 30004


server_params:
  ip: 127.0.0.1
  port: 5783
  policy: default_vllm
  offload_frequency: 0.8
  queue_frequency: 0.2
  accept_frequency: 0.0

ledger_params:
  initial_credit: 1000.0
  initial_staked: 0.0

models:
  - model_path: ~/Reasoning/Decentralized-Agents/models/DeepSeek-R1-Distill-Qwen-7B
    base_url: http://192.168.102.12:30004
    api_key: None

    gen_params:
      max_tokens: 8192
      temperature: 0.6
      top_p: 0.95
    
    dispatch_params:
      target_token_usage: 0.6
